server:
  port: 8081

spring:
  application:
    name: consumer-user-feign

eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/

feign:
  hystrix:
    enable: true