server:
  port: 8100

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-user-ribbon
    api-b:
      path: /api-b/**
      serviceId: consumer-user-feign