server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/